[package]
name = "simple_db"
version = "0.1.0"
authors = ["Fallensouls <122584482@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
downcast_macro_derive = {path = "./downcast_macro_derive"}

